name: Daily PageSpeed Report Update

on:
  schedule:
    # This cron job runs at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jinja2

      # Fetch PageSpeed data and generate reports
      - name: Generate PageSpeed reports
        env:
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
        run: |
          python .github/scripts/generate_pagespeed_report.py

      # Commit and push changes
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Automated daily update of PageSpeed reports'
          add: '*.html'
